package deilyquote;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER_MOMENTS.
 */
public class UserMoments {

    private Long id;
    private String language;
    private String personality;
    private String time;

    public UserMoments() {
    }

    public UserMoments(Long id) {
        this.id = id;
    }

    public UserMoments(Long id, String language, String personality, String time) {
        this.id = id;
        this.language = language;
        this.personality = personality;
        this.time = time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public String getPersonality() {
        return personality;
    }

    public void setPersonality(String personality) {
        this.personality = personality;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

}
