package deilyquote;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER_QUOTES.
 */
public class UserQuotes {

    private Long id;
    private String language;
    private String personality;
    private String personality2;
    private String personality3;
    private String quote;
    private String author;

    public UserQuotes() {
    }

    public UserQuotes(Long id) {
        this.id = id;
    }

    public UserQuotes(Long id, String language, String personality, String personality2, String personality3, String quote, String author) {
        this.id = id;
        this.language = language;
        this.personality = personality;
        this.personality2 = personality2;
        this.personality3 = personality3;
        this.quote = quote;
        this.author = author;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public String getPersonality() {
        return personality;
    }

    public void setPersonality(String personality) {
        this.personality = personality;
    }

    public String getPersonality2() {
        return personality2;
    }

    public void setPersonality2(String personality2) {
        this.personality2 = personality2;
    }

    public String getPersonality3() {
        return personality3;
    }

    public void setPersonality3(String personality3) {
        this.personality3 = personality3;
    }

    public String getQuote() {
        return quote;
    }

    public void setQuote(String quote) {
        this.quote = quote;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

}
