package deilyword;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import deilyword.UserMoments;
import deilyword.UserWords;

import deilyword.UserMomentsDao;
import deilyword.UserWordsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userMomentsDaoConfig;
    private final DaoConfig userWordsDaoConfig;

    private final UserMomentsDao userMomentsDao;
    private final UserWordsDao userWordsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userMomentsDaoConfig = daoConfigMap.get(UserMomentsDao.class).clone();
        userMomentsDaoConfig.initIdentityScope(type);

        userWordsDaoConfig = daoConfigMap.get(UserWordsDao.class).clone();
        userWordsDaoConfig.initIdentityScope(type);

        userMomentsDao = new UserMomentsDao(userMomentsDaoConfig, this);
        userWordsDao = new UserWordsDao(userWordsDaoConfig, this);

        registerDao(UserMoments.class, userMomentsDao);
        registerDao(UserWords.class, userWordsDao);
    }
    
    public void clear() {
        userMomentsDaoConfig.getIdentityScope().clear();
        userWordsDaoConfig.getIdentityScope().clear();
    }

    public UserMomentsDao getUserMomentsDao() {
        return userMomentsDao;
    }

    public UserWordsDao getUserWordsDao() {
        return userWordsDao;
    }

}
