package deilyword;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER_WORDS.
 */
public class UserWords {

    private Long id;
    private Integer IdWord;
    private String LanguageNew;
    private String LanguageDevice;
    private String Level;

    public UserWords() {
    }

    public UserWords(Long id) {
        this.id = id;
    }

    public UserWords(Long id, Integer IdWord, String LanguageNew, String LanguageDevice, String Level) {
        this.id = id;
        this.IdWord = IdWord;
        this.LanguageNew = LanguageNew;
        this.LanguageDevice = LanguageDevice;
        this.Level = Level;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getIdWord() {
        return IdWord;
    }

    public void setIdWord(Integer IdWord) {
        this.IdWord = IdWord;
    }

    public String getLanguageNew() {
        return LanguageNew;
    }

    public void setLanguageNew(String LanguageNew) {
        this.LanguageNew = LanguageNew;
    }

    public String getLanguageDevice() {
        return LanguageDevice;
    }

    public void setLanguageDevice(String LanguageDevice) {
        this.LanguageDevice = LanguageDevice;
    }

    public String getLevel() {
        return Level;
    }

    public void setLevel(String Level) {
        this.Level = Level;
    }

}
