package deilyword;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER_WORDS.
 */
public class UserWords {

    private Long id;
    private Integer IdWord;
    private String language;

    public UserWords() {
    }

    public UserWords(Long id) {
        this.id = id;
    }

    public UserWords(Long id, Integer IdWord, String language) {
        this.id = id;
        this.IdWord = IdWord;
        this.language = language;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getIdWord() {
        return IdWord;
    }

    public void setIdWord(Integer IdWord) {
        this.IdWord = IdWord;
    }

    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

}
